### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sagangwee** [ohjay/RolyPoly#1]
### Don't forget

- [x] Release camera after using so things don't break

### If we're planning to submit and present, we need to finish all of the following by noon:

- [x] Crop the RolyPoly icon
- [ ] Finish the interface for switching between modes (camera, identify, idle?)
- [ ] Preprocess images before they are saved to our "database" (standardize them and stuff)
- [ ] Set up the code in some activity to load all faces (or just the features?) from our filesystem
- [x] Detect faces (get images and array of bounding boxes within each image)
- [ ] Identify faces (search over faces in database)
- [x] Display names over people's faces during identification
- [ ] Display people's names and pictures on the screen after recognition (for demo purposes)
- [x] Write up Devpost
- [ ] Prepare for presentation and demos (we have an extra hour for this)
